apiVersion: apps/v1
kind: Deployment
metadata:
  name: livekit-agent
  namespace: ${NAMESPACE}
  labels:
    app: livekit-agent
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: livekit-agent
  template:
    metadata:
      labels:
        app: livekit-agent
    spec:
      containers:
      - name: livekit-agent
        image: ${CONTAINER_REGISTRY_URL}/livekit-agent:${BUILD_TAG}
        env:
        - name: LIVEKIT_API_KEY
          value: "${LIVEKIT_KEY}"
        - name: LIVEKIT_API_SECRET
          value: "${LIVEKIT_SECRET}"
        - name: LIVEKIT_URL
          value: "${LIVEKIT_URL}"
        - name: CARTESIA_API_KEY
          value: "${CARTESIA_API_KEY}"
        - name: DEEPGRAM_API_KEY
          value: "${DEEPGRAM_API_KEY}"
        - name: OPENAI_API_KEY
          value: "${OPENAI_API_KEY}"
        - name: DEEPSEEK_API_KEY
          value: "${DEEPSEEK_API_KEY}"                    
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5