apiVersion: v1
kind: Service
metadata:
  name: livekit-agent-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: livekit-agent
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP