version: "3"
output: interleaved
dotenv: [".env.local"]

tasks:
  post_create:
    desc: "Runs after this template is instantiated as a Sandbox or Bootstrap"
    vars:
      TOKEN_FILE: "hooks/useConnectionDetails.ts"
    cmds:
      - echo -e "Setting up sandbox..."
      - platforms: [darwin]
        cmd: sed -i "" "s/sandboxID = ''/sandboxID = '{{.LIVEKIT_SANDBOX_ID}}'/g" "{{.ROOT_DIR}}/{{.TOKEN_FILE}}"
      - platforms: [linux, windows]
        cmd: sed -i "s/sandboxID = ''/sandboxID = '{{.LIVEKIT_SANDBOX_ID}}'/g" "{{.ROOT_DIR}}/{{.TOKEN_FILE}}"
      - echo -e "\nYour React-Native voice assistant is ready to go!\n"

      - echo -e "Install the dependencies by running \"npm install\""
      - echo -e "To give it a try, run \"npx expo run:android\" or \"npx expo run:ios\" to run the app.\n"

      - echo -e "For more help view your project's README.md file or join our Slack community at https://livekit.io/join-slack."